apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: springboot-keyvault-csi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "788c14de-f874-4e61-b236-9e56f039681b" 
    keyvaultName: "keyVault8"  
    cloudName: "" 
    objects: |
      array:
      	- |
          objectName: "url"
          objectType: "secret"
        - |
          objectName: "password"
          objectType: "secret"
        - |
          objectName: "username"
          objectType: "secret"
    tenantId: "8d1157bb-1f96-415f-824b-ab0a29485d7d"

  secretObjects: 
    - data:
        - key: SPRING_DATASOURCE_URL
          objectName: "url"
        - key: SPRING_DATASOURCE_USERNAME
          objectName: "username"
        - key: SPRING_DATASOURCE_PASSWORD
          objectName: "password"
      secretName: springboot-secrets 
      type: Opaque 

