apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: quote-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend/multistage:latest 
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          volumeMounts:
            - name: backend-logs
              mountPath: /app/logs
      volumes:
        - name: backend-logs
          persistentVolumeClaim:
            claimName: backendlogs-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: quote-app
spec:
  type: NodePort 
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000 
