apiVersion: v1
kind: PersistentVolume
metadata:
  name: backendlogs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/backend-logs"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backendlogs-pvc
  namespace: quote-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: backendlogs-pv 
  storageClassName: "" 
