---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Start and Enable Nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Deploy Custom Web Page
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Restart Nginx

