- name: Create Azure VM
  hosts: localhost
  connection: local
  vars_files:
    - ./vars.yml

  tasks:
     - name: Create virtual network
       azure.azcollection.azure_rm_virtualnetwork:
         resource_group: "{{ rg_name }}"
         name: vnet
         address_prefixes: "10.0.0.0/16"

     - name: Add subnet
       azure.azcollection.azure_rm_subnet:
         resource_group: "{{ rg_name }}"
         name: subnet
         address_prefix: "10.0.1.0/24"
         virtual_network: vnet

     - name: Create public IP address
       azure.azcollection.azure_rm_publicipaddress:
         resource_group: "{{ rg_name }}"
         allocation_method: Static
         name: publicIP
       register: output_ip_address

     - name: Public IP of VM
       debug:
         msg: "The public IP is {{ output_ip_address.state.ip_address }}."

     - name: Store Public IP as a Host Variable
       set_fact:
         public_ip: "{{ output_ip_address.state.ip_address }}"

     - name: Debug public_ip variable
       debug:
         var: hostvars['localhost']['public_ip']

     - name: Create Network Security Group that allows SSH
       azure.azcollection.azure_rm_securitygroup:
         resource_group: "{{ rg_name }}"
         name: NSG
         rules:
           - name: SSH
             protocol: Tcp
             destination_port_range: 22
             access: Allow
             priority: 1000
             direction: Inbound
             source_address_prefix: "{{ allowed_ips }}"
             destination_address_prefix: "*"
           - name: HTTP
             protocol: Tcp
             destination_port_range: 80
             access: Allow
             priority: 1010
             direction: Inbound
             source_address_prefix: "*"
             destination_address_prefix: "*"

     - name: Create virtual network interface card
       azure.azcollection.azure_rm_networkinterface:
         resource_group: "{{ rg_name }}"
         name: NIC
         virtual_network: vnet
         subnet: subnet
         security_group: NSG
         ip_configurations:
          - name: ipconfig1
            public_ip_name: publicIP
            primary: yes

     - name: Create VM
       azure.azcollection.azure_rm_virtualmachine:
         resource_group: "{{ rg_name }}"
         name: VM
         vm_size: Standard_B1s
         admin_username: azureuser
         ssh_password_enabled: false
         ssh_public_keys:
           - path: /home/azureuser/.ssh/authorized_keys
             key_data: "{{ lookup('file', '~/.ssh/ansible_azure.pub') }}"
         network_interfaces: NIC
         image:
           offer: 0001-com-ubuntu-server-jammy
           publisher: Canonical
           sku: 22_04-lts
           version: latest
